image: shru/arch-love-release:heavy

variables:
  ITCHIO_USER: shru
  ITCHIO_GAME: cave-story-randomizer
  CHANNEL: $CI_COMMIT_REF_NAME

stages:
  - build-release

build-and-release:
  stage: build-release
  when: manual
  script:
    # I - Build
    - cd src
    - love-release -W
    # II - Release to itch.io
    - cd releases
    - FILE=$(ls *-win32.zip) ; butler push "$FILE" "$ITCHIO_USER/$ITCHIO_GAME:win32-$CHANNEL"
    # - FILE=$(ls *-win64.zip) ; butler push "$FILE" "$ITCHIO_USER/$ITCHIO_GAME:win64-$CHANNEL"
